apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app-python-helm.fullname" . }}-statefulset
spec:
  selector:
    matchLabels:
      name: {{ include "app-python-helm.fullname" . }}-statefulset
  serviceName: {{ include "app-python-helm.fullname" . }}-statefulset
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ include "app-python-helm.fullname" . }}-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ include "app-python-helm.fullname" . }}-statefulset
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}