apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-js
  labels:
    app: js
spec:
  serviceName: app-js
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  replicas: 3
  selector:
    matchLabels:
      app: js
  template:
    metadata:
      labels:
        app: js
    spec:
      containers:
      - name: app-js
        image: kernie/joke-js
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /usr/app/data
            name: js-data
      volumes:
        - name: js-data
          emptyDir: { }
